---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package_ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
